name: Build Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    container:
      image: node:26-slim
    
    steps:
      - uses: actions/checkout@v7

      - name: Install requirements
        run: |
          apt-get update && apt-get upgrade -y && \
          apt-get install meson build-essential -y

      - name: Configure
        run: |
          meson setup --buildtype=release build-release

      - name: Build
        run: |
          meson compile -C build-release

      - name: Package artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p release-artifacts
          cp build-release/ping release-artifacts/
          tar -czf ping-linux.tar.gz -C release-artifacts .
          echo "ARTIFACT_PATH=ping-linux.tar.gz" >> $GITHUB_ENV

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: ping-linux
          path: ping-linux.tar.gz
